name: cavebear
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - anndata
  - ipykernel
  - leidenalg
  - python-igraph
  - scanpy
   # R and R packages
  - r-base
  - r-data.table
  - r-ggplot2
  - r-stringr
  - r-vgam
  - r-rmisc
  - r-dplyr
  - r-optparse
  - cairo